apiVersion: v1
kind: Service
metadata:
  name: ai-operator
  labels:
    app: ai-operator
spec:
  ports:
    - port: 8005
      targetPort: 8005
      protocol: TCP
      name: http
  selector:
    app: ai-operator
  type: ClusterIP
