apiVersion: v1
kind: Service
metadata:
  name: jaeger-all-in-one-query
  namespace: observability
spec:
  selector:
    app: jaeger
  ports:
    - name: query
      port: 16686
      targetPort: 16686
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-all-in-one-otlp
  namespace: observability
spec:
  selector:
    app: jaeger
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
  type: ClusterIP
