apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: archaics

resources:
  - namespace.yaml
  - auth
  - db
  - product
  - payment
  - ai-operator
  - anomaly-detector



generatorOptions:
  disableNameSuffixHash: true
