apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: archaics

resources:
  - namespace.yaml
  - auth
  - db
  - product
  - ai-operator

secretGenerator:
  - name: archaics-secrets
    literals:
      - jwt-secret=archaIc-secret-key-2024
      - gemini-api-key=PLACEHOLDER_KEY

generatorOptions:
  disableNameSuffixHash: true
