apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: archaics

resources:
  - namespace.yaml
  - auth
  - db
  - product

secretGenerator:
  - name: archaics-secrets
    literals:
      - jwt-secret=archaIc-secret-key-2024

generatorOptions:
  disableNameSuffixHash: true
